-- 修复：为继承 BaseEntity 的表补充 deleted 列
ALTER TABLE sys_user ADD COLUMN IF NOT EXISTS deleted SMALLINT DEFAULT 0;
ALTER TABLE sys_role ADD COLUMN IF NOT EXISTS deleted SMALLINT DEFAULT 0;
ALTER TABLE plm_bom ADD COLUMN IF NOT EXISTS deleted SMALLINT DEFAULT 0;
ALTER TABLE plm_ecn ADD COLUMN IF NOT EXISTS deleted SMALLINT DEFAULT 0;

-- 补充其他可能缺失的表
ALTER TABLE plm_material_version ADD COLUMN IF NOT EXISTS deleted SMALLINT DEFAULT 0;
ALTER TABLE plm_bom_version ADD COLUMN IF NOT EXISTS deleted SMALLINT DEFAULT 0;
